name: Build YTUHD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl build-essential perl unzip xz-utils

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          bash $HOME/theos/bin/install-theos

      - name: Build package
        run: |
          make package FINALPACKAGE=1

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ytuhd-deb
          path: packages/*.deb
