name: Build YTUHD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: |
          export THEOS=/home/runner/theos
          make package FINALPACKAGE=1

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ytuhd-deb
          path: packages/*.deb
